<a href="https://colab.research.google.com/github/amrit-pratya/Deep_Learning_projects/blob/main/Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

In [3]:
neuron = nn.Linear(in_features=5, out_features=1)

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([2.0136], grad_fn=<ViewBackward0>)

In [6]:
# verify ..the formula
neuron.weight @ inputs + neuron.bias


tensor([2.0136], grad_fn=<AddBackward0>)

In [7]:
neuron.bias

Parameter containing:
tensor([0.0902], requires_grad=True)